### ISSUE TITLE
instructions are not clear 

### ISSUE THREAD

**Issue by subhash0x** [Lzaruss/Bot-Quora-Partner-program#1]
can you write step by step to use this script?

**Comment by Lzaruss** [comment]
Hi!
The only step you have to do is to start the script and login to your account, seconds later the script will automatically start asking questions (first of all you must have a file with questions, which in my case I have called questions.txt, 1 question per line).
If you need more help let me know

**Comment by subhash0x** [comment]
well do I need a proxy server in my browser or should I use Chromium?

**Comment by Lzaruss** [comment]
I dont know answer to that, i only use Chromium from Selenium
